= Starter tsup
:hide-uri-scheme:
:sectnums:
:toc: right
:toclevels: 4

:coreJs: https://github.com/zloirock/core-js
:csp: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

:enonicAssetService: https://developer.enonic.com/docs/xp/stable/runtime/engines/asset-service
:enonicAssetUrl: https://developer.enonic.com/docs/xp/stable/api/lib-portal#asseturl
:enonicCSP: https://developer.enonic.com/docs/content-studio/stable/security#content_security_policy
:enonicDevMode: https://developer.enonic.com/docs/xp/stable/apps/build-system#development_mode
:enonicLibStatic: https://developer.enonic.com/docs/static-asset-lib/master
:enonicReact4xp: https://developer.enonic.com/docs/react4xp/
:enonicStart: https://developer.enonic.com/start

:esbuildPluginPolyfillNode: https://www.npmjs.com/package/esbuild-plugin-polyfill-node
:excludingPackages: https://tsup.egoist.dev/#excluding-packages
:globalObject: https://developer.mozilla.org/en-US/docs/Glossary/Global_object
:globalThis: https://262.ecma-international.org/11.0/#sec-globalthis

:gradleContinuousBuild: https://docs.gradle.org/current/userguide/incremental_build.html#sec:task_input_output_continuous_build
:gradleIncrementalBuild: https://docs.gradle.org/current/userguide/incremental_build.html
:gradleNodePlugin: https://github.com/node-gradle/gradle-node-plugin
:gradleReleases: https://gradle.org/releases/
:gradleUpgradeWrapper: https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper

:nvm: https://github.com/nvm-sh/nvm
:tsupWatchMode: https://tsup.egoist.dev/#watch-mode
:userAgent: https://developer.mozilla.org/en-US/docs/Glossary/User_agent
:webpackCache: https://webpack.js.org/configuration/cache/

== Features

* Typescript support
* Fast build times (tsup uses esbuild and swc)
* Asyncronous (concurrent build targets)
* Transpiling
* Bundling
* Tree-shaking
* Polyfilling, injection and banner
* Code splitting (chunks)

== Create project

To setup a project locally, run the following command:

[source,bash]
----
enonic project create -r starter-tsup
----

TIP: *Don't have the Enonic CLI?* Visit the {enonicStart}[Getting started guide] to install it.

== Build environment

=== Enonic CLI

The best way of working with Enonic XP projects is to use the Enonic CLI.

TIP: *Don't have the Enonic CLI?* Visit the {enonicStart}[Getting started guide] to install it.

=== Gradle

We try to keep our starters up-to-date with the latest {gradleReleases}[Gradle releases].

==== Version

You can check which version of gradle is in use by issuing this command:

[source,bash]
----
./gradlew --version
----

==== Upgrade

You can upgrade your gradle wrapper by issuing this command:

[source,bash]
----
./gradlew wrapper --gradle-version latest
----

Read more about {gradleUpgradeWrapper}[Upgrading the Gradle Wrapper].

=== Node

==== Version

WARNING: Some node modules doesn't support the newest versions of Node (yet).

For example the `node-sass` currently doesn't support Node version newer than 16.

==== Gradle node plugin

The tsup-starter uses the {gradleNodePlugin}[Gradle node plugin].

The gradle node plugins is loaded like this:

.build.gradle
[source,gradle]
----
plugins {
	id 'com.github.node-gradle.node' version '5.0.0'
}
----

And configured like this:

.build.gradle
[source,gradle]
----
node {
	// Whether to download and install a specific Node.js version or not
	// If false, it will use the globally installed Node.js
	// If true, it will download node using above parameters
	// Note that npm is bundled with Node.js
	download = true

	// Version of node to download and install (only used if download is true)
	// It will be unpacked in the workDir
	version = "16.20.0"
}
----

Any gradle task that runs scripts in node should depend on npmInstall:

.build.gradle
[source,gradle]
----
task myTask(type: NpmTask) {
    dependsOn npmInstall
}
----

==== System Node

Sometimes you want to run node scripts directly (not via gradle). For example when running Enonic XP in <<DEV mode (watch)>>.

TIP: {nvm}[Node version manager] can be used to have multiple versions of Node at your fingertips.

In order to use the correct version of Node, use the following command:

[source,bash]
----
nvm use
----

It will use the version contained in the ./.nvmrc file:

..nvmrc
[source,bash]
----
16.20.0
----

=== Incremental build

"An important part of any build tool is the ability to avoid doing work that has already been done."
-- Gradle Inc

==== Continuous build

Gradle does support {gradleIncrementalBuild}[incremental build], but due to reasons I will explain: using gradle in {gradleContinuousBuild}[continuous mode] is NOT the most efficient option. Gradle can detect file changes, but it doesn't know much about the dependency tree of javascript files, aka which other files needs to be recompiled once a single javascript file is changed. Gradle will simply rebuild "everything" by calling:

[source,bash]
----
npm run build
----

tsup/esbuild doesn't support filesystem caching, like {webpackCache}[Webpack], but they do support {tsupWatchMode}[watch mode].

==== Watch mode

Tsup will watch files for changes and only recompile that file, and any files that depend on that file, and files that depend on them, and so on..., but nothing else, aka the minimal amout of recompilation for a "complete" build.

WARNING: However this does NOT produce a jar file, which is what Enonic XP requires to deploy apps.

TIP: To run new code WITHOUT redeploying an app, start the Enonic XP distribution in DEV mode.

==== DEV mode

Enonic XP can be run in a special mode known as {enonicDevMode}[development mode]. In this mode, XP will read files directly from their source locations (`build/resources/main`, and even `src/main/resources`).

CAUTION: In order for this to work Enonic XP needs to know, where those folders are. That information is contained within the jar file. So you need to make an initial deployment of your application jar file, and whenever you move your code tree on your file system.

CAUTION: Enonic XP will "fallback" to the jar file, if a file is not found in it's source locations. So when you delete a source file, it is probably a good idea to do a full build and redeploy a fresh jar file without the deleted file.

== Server-side code

The JavaScript ecosystem is advancing rapidly, using more and more modern features, which typically isn't supported everywhere (yet).

In order to use modern features, transpilers are used to convert modern code into more stable versions of ECMAScript, and polyfills are used to provide API's which are not present in the runtime environment.

NOTE: Currently the Enonic XP JavaScript framework only has limited `ECAMScript 6/2015` support and only support the `CommonJS module` (CJS) format.

=== Java libraries

In order to use Enonic XP java libraries in your code, there are some steps required:

:sectnums:
==== Include

Include the java library in

.build.gradle
[source,gradle]
----
dependencies {
    include "com.enonic.xp:lib-portal:${xpVersion}"
}
----

==== Externals

The java library jar file typically contain a CJS wrapper which is required at runtime.

The contents of the jar file is NOT available at compile time, so it cannot be bundled. Instead we tell the transpiler to treat the library import path as an external (expecting it to exist at runtime).

./tsup/server.ts
[source,typescript]
----
external: [
    /^\/lib\/xp\//,
]
----

==== Import

./src/main/resources/site/page/examplePage/examplePage.ts
[source,typescript]
----
import { getContent } from '/lib/xp/portal';

export function get() {
    const {
        displayName,
        page: {
            regions
        }
    } = getContent();
}
----

=== Node modules

You can use node modules in your code, but there are come steps/caveats to consider:

==== Installing

You can use the following command to install a node module you want to use:

[source,bash]
----
npm install --save sha.js
----

This will add `sha.js` under dependencies in the package.json file, and download and extract the package into node_modules/sha.js/

==== Bundling

By default starer-tsup bundles all imported modules {excludingPackages}[EXCEPT] dependencies and peerDependencies.

WARNING: Since sha.js is listed under dependencies, it will [red]#NOT# be bundled!

TIP: To fix that we have to list it under noExternals:

./tsup/server.ts
[source,typescript]
----
noExternal: [
    'sha.js',
],
----

==== Polyfill Node

CAUTION: Node modules are typically run in Node, and thus expect Node API's to be present, which is not always the case.

For example the `sha.js` module expects buffer to exist in the global scope, but it does NOT in the Enonic XP JavaScript framework runtime environment.

We can use {esbuildPluginPolyfillNode}[esbuild-plugin-polyfill-node] to selectively polyfill only the parts of Node that is used by the node module:

./tsup/server.ts
[source,typescript]
----
import { polyfillNode } from 'esbuild-plugin-polyfill-node';

esbuildPlugins: [
    polyfillNode: {
        globals: {
            buffer: true
        },
        polyfills: {
            buffer: true
        }
    }
]
----

==== The global object

Different JavaScript runtime environments have different properties on their {globalObject}[global object]

In addition they even have different ways of accessing the global object.

{globalThis}[globalThis], introduced in ES2020 aims to consolidate the increasingly fragmented ways of accessing the global object.

Some node modules support multiple runtime environments, and uses the properties on the global object to determine what runtime environment the code is running under.

CAUTION: One might be tempted to polyfill all the ways of accessing the global object, but that will typically break node modules that are trying to detect the runtime environment.

WARNING: To make matters worse, some of the polyfills themselves expect things to be a certain way.
For example the polyfilling of buffer only works if it can apply itself on the globals object.

IMPORTANT: In the Enonic XP JavaScript framework, each controller run in it's own "sandbox" environment, so there really isn't a global object, there is rather a controller scope "local" object.

TIP: In order for the buffer polyfill to work we can simply make a globalThis point to the controller scope:

./tsup/server.ts
[source,typescript]
----
esbuildOptions(options, context) {
    options.banner = {
        js: `const globalThis = (1, eval)('this');`
    };
}
----

==== Injection

Sometimes all you need to polyfill is a `single function` rather than a whole API.

{coreJs} provides a bunch of such minimal `single function` polyfills.

TIP: If you only use `the function` in a single place, you can simply import the polyfill in that single file.
But if you are using `the function` all over the place, you can use injection to make it work everywhere:

./tsup/server.ts
[source,typescript]
----
inject: [
    'node_modules/core-js/stable/array/includes.js'
]
----

==== Code splitting

CAUTION: Everthing you add via imports, polyfills, banners, injections, etc increases the size of the resources which need to be loaded into memory at runtime. The more you add, the longer the warmup time becomes.

In order to avoid loading the same code multiple times, shared code is split into chunk files, which are only loaded once, but can be used many times via require in the JavaScript controllers.

It sorta like all the shared code exists in the global scope and don't need to be loaded.

WARNING: An Enonic XP application jar file only has a single "root folder" which all libs are "merged" into, which can potentially cause file name collisions.

NOTE: Libraries typically avoid file name collisions by using their own "namespace" inside the /lib folder.

When it comes to files autogenerated by a build system, for example chunk files, they also need their own "namespace".

In starter-tsup we can "namespace" it's chunks like this:

./tsup/server.ts
[source,typescript]
----
esbuildOptions(options, context) {
    options.chunkNames = 'myAppChunks/[name]-[hash]';
}
----

=== Tree-shaking

The tools that supports tree-shaking typically only work with the `ECMAScript module` (ESM) format.

starter-tsup uses esbuild to transpile the sources into ESM so that tree-shaking can be applied.

Then it uses swc to transpile the code back to CJS (the format supported by Enonic XP JavaScript framework).

== Client-side

Client-side and server-side are web development terms that describe where application code runs.

When people talk about "the client-side", they typically just mean THEIR web browser, not considering other {userAgent}[User-Agents] like bots/robots/web-crawlers, headless browsers, legacy browsers or even other modern browser alternatives :)

In the context of build systems, the source code is processed in different ways, depending upon which `target plarform` the code is supposed to run on.

There are many ways of developing client-side code in Enonic XP:

* The most common way is to use the <<Assets>> folder.
* This can be improved upon by using <<Static,lib-static>>.
* It can be provided by <<Services>>, <<Site Mappings>>, <<Webapp>>, or <<Admin>>.
* Client-side code can be inlined in <<Components, controllers>>.
* Web frameworks like <<React>> can be used.
* <<Content Security Policy>> is enabled by default and can be configured for improved security.

=== Content Security Policy

{csp}[Content Security Policy (CSP)] makes it possible to configure what is allowed to run on the client-side. You can limit scripts, images, media and stylesheets. You can even configure if and how violations are reported.

Enonic XP has some configurable {enonicCSP}[Content Security Policy] defaults, but you can override these by using the `content-security-policy` response header (or a `<meta http-equiv="Content-Security-Policy"/>` tag in html head).

=== React

starter-tsup is able to transpile React TSX/JSX source files into JavaScript code for the browser.

The starter includes two main ways of doing this. Read more under <<Assets>>.

CAUTION: If you NEED Server-side Rendering (SSR), use {enonicReact4xp}[React4xp].

== Tools

=== Code completion

When programming, it's very useful to get `code completion` and <<Type checking>> directly in the code editor.
To enable this, IDE's will typically look for <<_tsconfig_json,tsconfig.json>> files. 

=== Type checking

In addition to `type checking` directly in the IDE, it's a good idea to make `type checking` part of the build process.
In starter-tsup this is set up via `pre` statements in the scripts section of the package.json file. Type checking is currently skipped for development builds.

The `check:types:*` scripts uses the same <<_tsconfig_json,tsconfig.json>> files as IDE's.

=== tsconfig.json

starter-tsup comes with three `tsconfig.json` files:

1. ${PROJECT_DIR}/tsconfig.json
2. ${PROJECT_DIR}/src/main/resources/assets/tsconfig.json
3. ${PROJECT_DIR}/src/main/resources/static/tsconfig.json

The `tsconfig.json` file at the root of the project is used for all code processing (except the assets and static folders), and is configured to match the Enonic XP server-side runtime environment.

The two `tsconfig.json` files in assets and static, should be identical, and is configured for client-side runtime environment.

WARNING: Do NOT set target in the ${PROJECT_DIR}/tsconfig.json, it will probably break the build. Target should always be set to 'es5' in the ${PROJECT_DIR}/tsup/server.ts file.

TIP: Sometimes a folder may contain both code for the server-side and the client-side. Using different include and exclude lists in multiple `tsconfig.*.json` files makes it possible to configure strict type-checking for all code in those folders, to be run as part of the build process.

CAUTION: It seems IDE's are only able to read a single `tsconfig.json` file per folder, so it's currently only possible to setup relaxed/permissive type checking when server and client side code is "mixed". Let us know if you discover a way to setup strict type-checking. 🙏

== Code Hierarchy

=== Admin

==== Tool

There is an exampleTool included in the starter.

==== Widgets

The starter includes examples for the following widget interfaces:

* Context panel
* Menuitem
* Dahboard

=== Assets

starter-tsup provides two main ways of providing client-side assets:

1. Either from the `assets` folder via the <<Service, Assets service>>
2. Or from the <<Static>> folder via <<Site Mappings>> or <<Webapp>> (even <<Admin>>)

TIP: We recommend using the <<Static>> folder, since it enables immuteable urls: Urls that can be cached "forever".

==== Assets service

WARNING: Any files in the assets folder are PUBLICLY available to EVERYONE via the {enonicAssetService}[Assets service]. If you need some security, do NOT put files in the assets folder. Rather put them somewhere else, and write your own controllers, and implement some security.

TIP: Any {enonicAssetUrl}[assetUrl] includes a build-id hash number. Which means, everytime you deploy a new build, the url changes. So even though the asset files are probably [red]#NOT changed#, they are still re-downloaded by the browser. Which is why we recommend using the <<Static>> folder instead.

==== Static

Files in the Static folder are not available via the <<Assets service>>. Instead they are made available via the {enonicLibStatic}[Static Assets Library].

In order to enable immuteable urls, a contenthash is added to the files names at compile time. The contenthash is generated from the file content (and location) and only changes, if the content (or location) of the file changes. This means that the browser can cache the asset "forever", and everytime it encounters the url, it can simply load the asset from it's cache.

Whenever you change a file, it will have a new contenthash, and thus a new url. In order for the browser to load the new url, the html repsonse from the server needs to provide the new url. This is made possible by a `manifest` file, which lists what the current contenthash is.

There are many ways of serving the files from the Static folder to the browser. The starter contains examples on how it can be done.

If you are writing code inside the <<Site>> folder, we recommend using `/lib/getImmuteableSiteUrl`.

If you are writing code inside the <<Webapp>> folder, we recommend using `/webapp/getImmuteableWebappUrl`.

If you are writing code inside the <<Admin>> folder, we recommend using `/admin/tools/exampleTool/getImmuteableAdminUrl`.

=== Error

The starter includes an example error controller.

=== I18n

The starter includes a couple phrases files.

=== Lib

The starter includes several lib examples.

=== Services

The starter includes an example service.

=== Site

==== Components

===== Page

TODO

===== Layout

TODO

===== Part

TODO

==== Site Mappings

TODO

=== Tasks

TODO

=== Webapp

TODO
